### ISSUE TITLE
Facing 2 issues when launching the wallet on Ios device

### ISSUE THREAD

**Issue by ThomasLuuu** [Sphereon-Opensource/ssi-mobile-wallet#49] opened 2023-03-09 09:01 UTC
I'm facing 2 issues when launching the wallet on my phone.
![2a3ed015-7534-45d6-b807-08a885c9ce73](https://user-images.githubusercontent.com/56161180/223972199-de3539f1-2767-4f62-bcbe-c2d90efaeab1.jpg)
![e5285104-8917-4e65-99c4-0e58b07178af](https://user-images.githubusercontent.com/56161180/223972220-6a5ee731-9046-430e-8aad-e74765e333cf.jpg)

**Comment by ThomasLuuu** [comment] 2023-03-09 09:02
I have woked around and the seed property come from ['RNRandomBytes.seed'].

**Comment by nklomp** [comment] 2023-03-09 13:28
Hi @ThomasLuuu Unfortunately IOS is not fully tested at this moment. We have some updates coming in from our SSI-SDK after which we will be looking into IOS builds. We are also aware of some UI/UX issues in IOS with the app right now.

I expect an updated develop branch this week, which hopefully also fixes the above. If not it probably is going to be roughly 2 weeks from now, as we need it to work in 3 weeks. Sorry for that.

**Comment by siacomuzzi** [comment] 2023-04-18 16:47
Hello, I'm facing similar issues while trying to run the `develop` branch in iOS. Should I use a different branch?

**Comment by nklomp** [comment] 2023-04-18 16:55
Hi @siacomuzzi, yes you need this branch: https://github.com/Sphereon-Opensource/ssi-mobile-wallet/pull/64
Be aware however that the OpenID4VP flow is being replaced currently with our final designs, and that you cannot continue that flow on IOS currently (biometric/faceid issue). There are some other issues we are aware of in IOS, which will be fixed next 2 weeks.

The IOS branch is: https://github.com/Sphereon-Opensource/ssi-mobile-wallet/tree/WAL-485_ios-build

**Comment by siacomuzzi** [comment] 2023-04-18 17:25
Many thanks for the prompt reply.
I'm afraid I'm still experiencing the same errors. Perhaps I'm doing something wrong. These are my repro steps:

```
cd ssi-mobile-wallet/
rm -rf node_modules
git checkout -b WAL-485_ios-build
yarn
npx expo start
```

Then, I scan QR code with my iOS camera and got the referenced errors in the Expo Go app.

**Comment by nklomp** [comment] 2023-04-18 17:40
Hmzz, @sanderPostma could you assist here?

The NativeEventEmitter is odd, as that should be fixed in IOS builds (@sanderPostma are there uncommitted changes by any chance?)

**Comment by sanderPostma** [comment] 2023-04-19 07:21
For iOS, I usually build the app on a Mac using XCode and selecting the Product -> Run option from the menu. (If I want to publish it on TestFlight, I choose Product -> Archive).  This process has worked well for me on the WAL-485_ios-build branch.
After updating my git repository, I also run "cd ios && pod install" on the command line to update the dependencies.

Today, I plan to test starting the app from the command line.

**Comment by siacomuzzi** [comment] 2023-04-19 10:47
Oh, I was following the instructions described in the [readme file](https://github.com/Sphereon-Opensource/ssi-mobile-wallet/tree/WAL-485_ios-build#requirements). Are you saying that I should use Xcode + TestFlight instead of Expo Go?

Also, I'm unable to build the project in Xcode v14.2 (Ventura)... Should I need a specific version?

<img width="266" alt="image" src="https://user-images.githubusercontent.com/178506/233051734-f4402500-b676-41eb-a2ae-f5d58231ab04.png"> <img width="206" alt="image" src="https://user-images.githubusercontent.com/178506/233051922-06990d76-bf43-477a-8c73-ecf2767de13f.png">

**Comment by sanderPostma** [comment] 2023-04-19 18:33
@siacomuzzi 
I am also using XCode 14.2, and the project is ./ios/SphereonWallet.xcodeproj.  I'd need to retest in a clean environment to see if I can reproduce your issue,
What does "expo run:ios" or "npx expo run:ios" do for you?

**Comment by siacomuzzi** [comment] 2023-04-20 14:39
I was able to build the app and execute it with the Xcode Simulator but it looks like the "Create PIN code" screen isn't working as expected (it's ignoring my input).
Also, I can't execute it in my iPhone:

<img width="293" alt="image" src="https://user-images.githubusercontent.com/178506/233398714-00d8a5e0-2707-4601-ae01-d198a53a7f21.png">

But don't worry, as I said before, the only plan was to test my [JWT VC Presentation Profile](https://identity.foundation/jwt-vc-presentation-profile/) implementation, I can wait until you have the app published in the Apple Store.

Thank you guys!

**Comment by siacomuzzi** [comment] 2023-04-20 14:51
After updating Xcode and re-installing Ruby/CocoaPods I was able to run your app in my phone 🎉 

<img width="300" src="https://user-images.githubusercontent.com/178506/233403776-4dec106e-eb8f-4ef8-9a2d-00c6d3f3e5c6.png">

Thank you guys, great work!

**Comment by siacomuzzi** [comment] 2023-04-20 15:50
You can play with this tool: https://verifiablecredentials.dev/presentation
I tried the presentation flow with MS Authenticator and it works as expected.

**Comment by nklomp** [comment] 2023-04-20 17:24
Cool will do. Yeah ours works as well with MS Authenticator, although we have to use the Presentation Definitions really simple, because otherwise Authenticator just doesn't know how to handle it. We need to setup the well-known DID for the RP to get rid of the warning (more a lack of time ;) )

**Comment by siacomuzzi** [comment] 2023-04-20 17:28
Right, for MS Authenticator you must to use PEXv1 (because it's required by JWT VC Presentation Profile).
FYI: The well-known DID for the tool is available here: https://present.verifiablecredentials.dev/.well-known/did-configuration.json

**Comment by nklomp** [comment] 2023-04-21 18:50
@siacomuzzi just wanted to let you know that the share flow and iOS branches have been merged. We do need to test it ourselves on iOS some more next week, but current develop should work fully for the share flow (with some UI/UX issues we still need to address on iOS)

**Comment by siacomuzzi** [comment] 2023-04-24 10:26
Great, I've switched to the `develop` branch and I was able to run the app on my phone.

**Closed** 2023-04-26 15:26 UTC
